package org.anaolabs.jpa.intotek.model;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="DOMAINS")
public class Domains {
	@Basic
	@Column(nullable=false)
	private Date created;

	@Id
	@Column(name="ID_DOMAIN")
	private long idDomain;

	@Basic
	@Column(length=100)
	private String name;


	public Domains() {
	}

	public Domains(long idDomain) {
		this.idDomain = idDomain;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public long getIdDomain() {
		return idDomain;
	}

	public void setIdDomain(long idDomain) {
		this.idDomain = idDomain;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}
}