INSERT 
 INTO DOMAIN(NAME, CREATED)
 VALUES('BigData', STR_TO_DATE('18,4,2015','%d,%m,%Y'))
;
INSERT 
 INTO DOMAIN(NAME, CREATED)
 VALUES('NoSql', STR_TO_DATE('18,4,2015','%d,%m,%Y'))
;
INSERT 
 INTO DOMAIN(NAME, CREATED)
 VALUES('Machine Learning', STR_TO_DATE('18,4,2015','%d,%m,%Y'))
;