package org.anaolabs.easytrust.model.etdwh;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="ET_DWH", name="CLIENT")
public class Client {
	@Basic
	@Column(length=6)
	private int cliagentlicencecount;

	@Basic
	@Column(length=1)
	private String clienabled;

	@Id
	@Column(length=4)
	private int cliid;

	@Basic
	@Column(length=2000)
	private String clilogo;


	public Client() {
	}

	public Client(int cliid) {
		this.cliid = cliid;
	}

	public int getCliagentlicencecount() {
		return cliagentlicencecount;
	}

	public void setCliagentlicencecount(int cliagentlicencecount) {
		this.cliagentlicencecount = cliagentlicencecount;
	}

	public String getClienabled() {
		return clienabled;
	}

	public void setClienabled(String clienabled) {
		this.clienabled = clienabled;
	}

	public int getCliid() {
		return cliid;
	}

	public void setCliid(int cliid) {
		this.cliid = cliid;
	}

	public String getClilogo() {
		return clilogo;
	}

	public void setClilogo(String clilogo) {
		this.clilogo = clilogo;
	}
}