package org.anaolabs.easytrust.model.etdwh;

import java.io.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="ET_DWH", name="ORGANISATION")
@IdClass(org.anaolabs.easytrust.model.etdwh.Organisation.Id.class)
public class Organisation {
	@Basic
	@Column(length=4)
	private int cliid;

	@Id
	@Column(length=22)
	private long datekey;

	@Id
	@Column(length=6)
	private int organisationid;

	@Basic
	@Column(length=32)
	private String organisationlevel;

	@Basic
	private String organisationname;

	@Basic
	@Column(length=6)
	private int organisationparentid;

	@Basic
	@Column(length=4000)
	private String organisationpath;

	@Basic
	@Column(length=32)
	private String organisationtype;


	public Organisation() {
	}

	public Organisation(long datekey, int organisationid) {
		this.datekey = datekey;
		this.organisationid = organisationid;
	}

	public int getCliid() {
		return cliid;
	}

	public void setCliid(int cliid) {
		this.cliid = cliid;
	}

	public long getDatekey() {
		return datekey;
	}

	public void setDatekey(long datekey) {
		this.datekey = datekey;
	}

	public int getOrganisationid() {
		return organisationid;
	}

	public void setOrganisationid(int organisationid) {
		this.organisationid = organisationid;
	}

	public String getOrganisationlevel() {
		return organisationlevel;
	}

	public void setOrganisationlevel(String organisationlevel) {
		this.organisationlevel = organisationlevel;
	}

	public String getOrganisationname() {
		return organisationname;
	}

	public void setOrganisationname(String organisationname) {
		this.organisationname = organisationname;
	}

	public int getOrganisationparentid() {
		return organisationparentid;
	}

	public void setOrganisationparentid(int organisationparentid) {
		this.organisationparentid = organisationparentid;
	}

	public String getOrganisationpath() {
		return organisationpath;
	}

	public void setOrganisationpath(String organisationpath) {
		this.organisationpath = organisationpath;
	}

	public String getOrganisationtype() {
		return organisationtype;
	}

	public void setOrganisationtype(String organisationtype) {
		this.organisationtype = organisationtype;
	}


	/**
	 * Application identity class for: org.anaolabs.easytrust.model.etdwh.Organisation
	 *
	 * Auto-generated by:
	 * org.apache.openjpa.enhance.ApplicationIdTool
	 */
	public static class Id implements Serializable {
		static {
			// register persistent class in JVM
			try { Class.forName("org.anaolabs.easytrust.model.etdwh.Organisation"); }
			catch(Exception e) {}
		}
	
		public long datekey;
		public int organisationid;
	
		public Id() {
		}
	
		public Id(String str) {
			fromString(str);
		}
	
		public long getDatekey() {
			return datekey;
		}
	
		public void setDatekey(long datekey) {
			this.datekey = datekey;
		}
	
		public int getOrganisationid() {
			return organisationid;
		}
	
		public void setOrganisationid(int organisationid) {
			this.organisationid = organisationid;
		}
	
		public String toString() {
			return String.valueOf(datekey)
				+ "::" + String.valueOf(organisationid);
		}
	
		public int hashCode() {
			int rs = 17;
			rs = rs * 37 + (int) (datekey ^ (datekey >>> 32));
			rs = rs * 37 + organisationid;
			return rs;
		}
	
		public boolean equals(Object obj) {
			if(this == obj)
				return true;
			if(obj == null || obj.getClass() != getClass())
				return false;
	
			Id other = (Id) obj;
			return (datekey == other.datekey)
				&& (organisationid == other.organisationid);
		}
	
		private void fromString(String str) {
			Tokenizer toke = new Tokenizer(str);
			str = toke.nextToken();
			datekey = Long.parseLong(str);
			str = toke.nextToken();
			organisationid = Integer.parseInt(str);
		}
	
		protected static class Tokenizer {
			private final String str;
			private int last;
	
			public Tokenizer (String str) {
				this.str = str;
			}
	
			public String nextToken () {
				int next = str.indexOf("::", last);
				String part;
				if(next == -1) {
					part = str.substring(last);
					last = str.length();
				} else {
					part = str.substring(last, next);
					last = next + 2;
				}
				return part;
			}
		}
	}
}