package org.anaolabs.easytrust.model.etdwh;

import java.io.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="ET_DWH", name="PRODUCT")
@IdClass(org.anaolabs.easytrust.model.etdwh.Product.Id.class)
public class Product {
	@Basic
	@Column(length=4)
	private int cliid;

	@Id
	@Column(length=22)
	private long datekey;

	@Basic
	private String productcategory;

	@Basic
	@Column(columnDefinition="DATE")
	private Date productcreationdate;

	@Basic
	private String productdbedition;

	@Basic
	@Column(length=4000)
	private String productdbglobalname;

	@Basic
	@Column(length=100)
	private String productdbisarchivelog;

	@Basic
	@Column(length=50)
	private String productdbisdowngradable;

	@Basic
	@Column(length=64)
	private String productdbname;

	@Basic
	@Column(length=50)
	private String productdbrole;

	@Basic
	@Column(length=32)
	private String productdbtype;

	@Basic
	private String productdbversion;

	@Basic
	private String producteditor;

	@Id
	@Column(length=12)
	private long productid;

	@Basic
	@Column(columnDefinition="DATE")
	private Date productinstancedate;

	@Basic
	@Column(length=64)
	private String productinstancehostname;

	@Basic
	@Column(length=100)
	private String productinstanceismonitored;

	@Basic
	@Column(length=500)
	private String productinstancename;

	@Basic
	@Column(length=200)
	private String productinstancestatus;

	@Basic
	private String productname;

	@Basic
	@Column(length=22)
	private long productnameid;

	@Basic
	@Column(length=32)
	private String productnameshortcurt;

	@Basic
	@Column(length=6)
	private int serverid;


	public Product() {
	}

	public Product(long datekey, long productid) {
		this.datekey = datekey;
		this.productid = productid;
	}

	public int getCliid() {
		return cliid;
	}

	public void setCliid(int cliid) {
		this.cliid = cliid;
	}

	public long getDatekey() {
		return datekey;
	}

	public void setDatekey(long datekey) {
		this.datekey = datekey;
	}

	public String getProductcategory() {
		return productcategory;
	}

	public void setProductcategory(String productcategory) {
		this.productcategory = productcategory;
	}

	public Date getProductcreationdate() {
		return productcreationdate;
	}

	public void setProductcreationdate(Date productcreationdate) {
		this.productcreationdate = productcreationdate;
	}

	public String getProductdbedition() {
		return productdbedition;
	}

	public void setProductdbedition(String productdbedition) {
		this.productdbedition = productdbedition;
	}

	public String getProductdbglobalname() {
		return productdbglobalname;
	}

	public void setProductdbglobalname(String productdbglobalname) {
		this.productdbglobalname = productdbglobalname;
	}

	public String getProductdbisarchivelog() {
		return productdbisarchivelog;
	}

	public void setProductdbisarchivelog(String productdbisarchivelog) {
		this.productdbisarchivelog = productdbisarchivelog;
	}

	public String getProductdbisdowngradable() {
		return productdbisdowngradable;
	}

	public void setProductdbisdowngradable(String productdbisdowngradable) {
		this.productdbisdowngradable = productdbisdowngradable;
	}

	public String getProductdbname() {
		return productdbname;
	}

	public void setProductdbname(String productdbname) {
		this.productdbname = productdbname;
	}

	public String getProductdbrole() {
		return productdbrole;
	}

	public void setProductdbrole(String productdbrole) {
		this.productdbrole = productdbrole;
	}

	public String getProductdbtype() {
		return productdbtype;
	}

	public void setProductdbtype(String productdbtype) {
		this.productdbtype = productdbtype;
	}

	public String getProductdbversion() {
		return productdbversion;
	}

	public void setProductdbversion(String productdbversion) {
		this.productdbversion = productdbversion;
	}

	public String getProducteditor() {
		return producteditor;
	}

	public void setProducteditor(String producteditor) {
		this.producteditor = producteditor;
	}

	public long getProductid() {
		return productid;
	}

	public void setProductid(long productid) {
		this.productid = productid;
	}

	public Date getProductinstancedate() {
		return productinstancedate;
	}

	public void setProductinstancedate(Date productinstancedate) {
		this.productinstancedate = productinstancedate;
	}

	public String getProductinstancehostname() {
		return productinstancehostname;
	}

	public void setProductinstancehostname(String productinstancehostname) {
		this.productinstancehostname = productinstancehostname;
	}

	public String getProductinstanceismonitored() {
		return productinstanceismonitored;
	}

	public void setProductinstanceismonitored(String productinstanceismonitored) {
		this.productinstanceismonitored = productinstanceismonitored;
	}

	public String getProductinstancename() {
		return productinstancename;
	}

	public void setProductinstancename(String productinstancename) {
		this.productinstancename = productinstancename;
	}

	public String getProductinstancestatus() {
		return productinstancestatus;
	}

	public void setProductinstancestatus(String productinstancestatus) {
		this.productinstancestatus = productinstancestatus;
	}

	public String getProductname() {
		return productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public long getProductnameid() {
		return productnameid;
	}

	public void setProductnameid(long productnameid) {
		this.productnameid = productnameid;
	}

	public String getProductnameshortcurt() {
		return productnameshortcurt;
	}

	public void setProductnameshortcurt(String productnameshortcurt) {
		this.productnameshortcurt = productnameshortcurt;
	}

	public int getServerid() {
		return serverid;
	}

	public void setServerid(int serverid) {
		this.serverid = serverid;
	}


	/**
	 * Application identity class for: org.anaolabs.easytrust.model.etdwh.Product
	 *
	 * Auto-generated by:
	 * org.apache.openjpa.enhance.ApplicationIdTool
	 */
	public static class Id implements Serializable {
		static {
			// register persistent class in JVM
			try { Class.forName("org.anaolabs.easytrust.model.etdwh.Product"); }
			catch(Exception e) {}
		}
	
		public long datekey;
		public long productid;
	
		public Id() {
		}
	
		public Id(String str) {
			fromString(str);
		}
	
		public long getDatekey() {
			return datekey;
		}
	
		public void setDatekey(long datekey) {
			this.datekey = datekey;
		}
	
		public long getProductid() {
			return productid;
		}
	
		public void setProductid(long productid) {
			this.productid = productid;
		}
	
		public String toString() {
			return String.valueOf(datekey)
				+ "::" + String.valueOf(productid);
		}
	
		public int hashCode() {
			int rs = 17;
			rs = rs * 37 + (int) (datekey ^ (datekey >>> 32));
			rs = rs * 37 + (int) (productid ^ (productid >>> 32));
			return rs;
		}
	
		public boolean equals(Object obj) {
			if(this == obj)
				return true;
			if(obj == null || obj.getClass() != getClass())
				return false;
	
			Id other = (Id) obj;
			return (datekey == other.datekey)
				&& (productid == other.productid);
		}
	
		private void fromString(String str) {
			Tokenizer toke = new Tokenizer(str);
			str = toke.nextToken();
			datekey = Long.parseLong(str);
			str = toke.nextToken();
			productid = Long.parseLong(str);
		}
	
		protected static class Tokenizer {
			private final String str;
			private int last;
	
			public Tokenizer (String str) {
				this.str = str;
			}
	
			public String nextToken () {
				int next = str.indexOf("::", last);
				String part;
				if(next == -1) {
					part = str.substring(last);
					last = str.length();
				} else {
					part = str.substring(last, next);
					last = next + 2;
				}
				return part;
			}
		}
	}
}