package org.anaolabs.easytrust.model.etdwh;

import java.io.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="ET_DWH", name="SERVER")
@IdClass(org.anaolabs.easytrust.model.etdwh.Server.Id.class)
public class Server {
	@Basic
	@Column(length=4)
	private int cliid;

	@Id
	@Column(length=22)
	private long datekey;

	@Basic
	@Column(length=100)
	private String serveragentup;

	@Basic
	@Column(length=50)
	private String serveragentversion;

	@Basic
	@Column(length=100)
	private String servercategory;

	@Basic
	@Column(length=64)
	private String serverclustername;

	@Basic
	@Column(length=4, scale=1)
	private double servercorecount;

	@Basic
	@Column(length=4, scale=1)
	private double servercorecountwithcorefactor;

	@Basic
	@Column(length=1, scale=3)
	private double servercorefactorapplied;

	@Basic
	@Column(length=32)
	private String servercountry;

	@Basic
	private String servercpucountbypartition;

	@Basic
	private String servercpupoolactive;

	@Basic
	private String servercpupoolcapacity;

	@Basic
	@Column(length=100)
	private String servercriticity;

	@Basic
	private String serverduty;

	@Basic
	private String servergroup;

	@Basic
	@Column(length=100)
	private String servergrouptype;

	@Id
	@Column(length=6)
	private int serverid;

	@Basic
	@Column(length=100)
	private String serverisactive;

	@Basic
	@Column(length=100)
	private String serverisimported;

	@Basic
	@Column(length=100)
	private String serverislmonly;

	@Basic
	@Column(length=100)
	private String serverisvirtualized;

	@Basic
	private String serverlabel;

	@Basic
	@Column(length=5)
	private int serverlifecheckfrequency;

	@Basic
	private String servermanufacturer;

	@Basic
	private String servermaxcpupartition;

	@Basic
	private String servermaxcpupool;

	@Basic
	@Column(length=3)
	private int servermaxsocket;

	@Basic
	private String servermodel;

	@Basic
	private String servername;

	@Basic
	@Column(length=22)
	private long serveroperatingsystemid;

	@Basic
	@Column(length=32)
	private String serveroperatingsystemname;

	@Basic
	@Column(length=32)
	private String serveroperatingsystemversion;

	@Basic
	private String serverpartitioninfo;

	@Basic
	private String serverpartitionmode;

	@Basic
	private String serverpartitiontype;

	@Basic
	private String serverpoolname;

	@Basic
	@Column(length=6)
	private int serverprocessorcount;

	@Basic
	@Column(length=20)
	private String serverprocessorfrequency;

	@Basic
	@Column(length=100)
	private String serverprocessorsmtactive;

	@Basic
	@Column(length=22)
	private long serverprocessorthreadbycore;

	@Basic
	private String serverprocessortype;

	@Basic
	@Column(columnDefinition="DATE")
	private Date serverpurchasedate;

	@Basic
	@Column(length=12)
	private String serverramsize;

	@Basic
	private String servertype;

	@Basic
	@Column(length=22)
	private long servervirtualizationid;

	@Basic
	@Column(length=32)
	private String servervirtualizationname;


	public Server() {
	}

	public Server(long datekey, int serverid) {
		this.datekey = datekey;
		this.serverid = serverid;
	}

	public int getCliid() {
		return cliid;
	}

	public void setCliid(int cliid) {
		this.cliid = cliid;
	}

	public long getDatekey() {
		return datekey;
	}

	public void setDatekey(long datekey) {
		this.datekey = datekey;
	}

	public String getServeragentup() {
		return serveragentup;
	}

	public void setServeragentup(String serveragentup) {
		this.serveragentup = serveragentup;
	}

	public String getServeragentversion() {
		return serveragentversion;
	}

	public void setServeragentversion(String serveragentversion) {
		this.serveragentversion = serveragentversion;
	}

	public String getServercategory() {
		return servercategory;
	}

	public void setServercategory(String servercategory) {
		this.servercategory = servercategory;
	}

	public String getServerclustername() {
		return serverclustername;
	}

	public void setServerclustername(String serverclustername) {
		this.serverclustername = serverclustername;
	}

	public double getServercorecount() {
		return servercorecount;
	}

	public void setServercorecount(double servercorecount) {
		this.servercorecount = servercorecount;
	}

	public double getServercorecountwithcorefactor() {
		return servercorecountwithcorefactor;
	}

	public void setServercorecountwithcorefactor(double servercorecountwithcorefactor) {
		this.servercorecountwithcorefactor = servercorecountwithcorefactor;
	}

	public double getServercorefactorapplied() {
		return servercorefactorapplied;
	}

	public void setServercorefactorapplied(double servercorefactorapplied) {
		this.servercorefactorapplied = servercorefactorapplied;
	}

	public String getServercountry() {
		return servercountry;
	}

	public void setServercountry(String servercountry) {
		this.servercountry = servercountry;
	}

	public String getServercpucountbypartition() {
		return servercpucountbypartition;
	}

	public void setServercpucountbypartition(String servercpucountbypartition) {
		this.servercpucountbypartition = servercpucountbypartition;
	}

	public String getServercpupoolactive() {
		return servercpupoolactive;
	}

	public void setServercpupoolactive(String servercpupoolactive) {
		this.servercpupoolactive = servercpupoolactive;
	}

	public String getServercpupoolcapacity() {
		return servercpupoolcapacity;
	}

	public void setServercpupoolcapacity(String servercpupoolcapacity) {
		this.servercpupoolcapacity = servercpupoolcapacity;
	}

	public String getServercriticity() {
		return servercriticity;
	}

	public void setServercriticity(String servercriticity) {
		this.servercriticity = servercriticity;
	}

	public String getServerduty() {
		return serverduty;
	}

	public void setServerduty(String serverduty) {
		this.serverduty = serverduty;
	}

	public String getServergroup() {
		return servergroup;
	}

	public void setServergroup(String servergroup) {
		this.servergroup = servergroup;
	}

	public String getServergrouptype() {
		return servergrouptype;
	}

	public void setServergrouptype(String servergrouptype) {
		this.servergrouptype = servergrouptype;
	}

	public int getServerid() {
		return serverid;
	}

	public void setServerid(int serverid) {
		this.serverid = serverid;
	}

	public String getServerisactive() {
		return serverisactive;
	}

	public void setServerisactive(String serverisactive) {
		this.serverisactive = serverisactive;
	}

	public String getServerisimported() {
		return serverisimported;
	}

	public void setServerisimported(String serverisimported) {
		this.serverisimported = serverisimported;
	}

	public String getServerislmonly() {
		return serverislmonly;
	}

	public void setServerislmonly(String serverislmonly) {
		this.serverislmonly = serverislmonly;
	}

	public String getServerisvirtualized() {
		return serverisvirtualized;
	}

	public void setServerisvirtualized(String serverisvirtualized) {
		this.serverisvirtualized = serverisvirtualized;
	}

	public String getServerlabel() {
		return serverlabel;
	}

	public void setServerlabel(String serverlabel) {
		this.serverlabel = serverlabel;
	}

	public int getServerlifecheckfrequency() {
		return serverlifecheckfrequency;
	}

	public void setServerlifecheckfrequency(int serverlifecheckfrequency) {
		this.serverlifecheckfrequency = serverlifecheckfrequency;
	}

	public String getServermanufacturer() {
		return servermanufacturer;
	}

	public void setServermanufacturer(String servermanufacturer) {
		this.servermanufacturer = servermanufacturer;
	}

	public String getServermaxcpupartition() {
		return servermaxcpupartition;
	}

	public void setServermaxcpupartition(String servermaxcpupartition) {
		this.servermaxcpupartition = servermaxcpupartition;
	}

	public String getServermaxcpupool() {
		return servermaxcpupool;
	}

	public void setServermaxcpupool(String servermaxcpupool) {
		this.servermaxcpupool = servermaxcpupool;
	}

	public int getServermaxsocket() {
		return servermaxsocket;
	}

	public void setServermaxsocket(int servermaxsocket) {
		this.servermaxsocket = servermaxsocket;
	}

	public String getServermodel() {
		return servermodel;
	}

	public void setServermodel(String servermodel) {
		this.servermodel = servermodel;
	}

	public String getServername() {
		return servername;
	}

	public void setServername(String servername) {
		this.servername = servername;
	}

	public long getServeroperatingsystemid() {
		return serveroperatingsystemid;
	}

	public void setServeroperatingsystemid(long serveroperatingsystemid) {
		this.serveroperatingsystemid = serveroperatingsystemid;
	}

	public String getServeroperatingsystemname() {
		return serveroperatingsystemname;
	}

	public void setServeroperatingsystemname(String serveroperatingsystemname) {
		this.serveroperatingsystemname = serveroperatingsystemname;
	}

	public String getServeroperatingsystemversion() {
		return serveroperatingsystemversion;
	}

	public void setServeroperatingsystemversion(String serveroperatingsystemversion) {
		this.serveroperatingsystemversion = serveroperatingsystemversion;
	}

	public String getServerpartitioninfo() {
		return serverpartitioninfo;
	}

	public void setServerpartitioninfo(String serverpartitioninfo) {
		this.serverpartitioninfo = serverpartitioninfo;
	}

	public String getServerpartitionmode() {
		return serverpartitionmode;
	}

	public void setServerpartitionmode(String serverpartitionmode) {
		this.serverpartitionmode = serverpartitionmode;
	}

	public String getServerpartitiontype() {
		return serverpartitiontype;
	}

	public void setServerpartitiontype(String serverpartitiontype) {
		this.serverpartitiontype = serverpartitiontype;
	}

	public String getServerpoolname() {
		return serverpoolname;
	}

	public void setServerpoolname(String serverpoolname) {
		this.serverpoolname = serverpoolname;
	}

	public int getServerprocessorcount() {
		return serverprocessorcount;
	}

	public void setServerprocessorcount(int serverprocessorcount) {
		this.serverprocessorcount = serverprocessorcount;
	}

	public String getServerprocessorfrequency() {
		return serverprocessorfrequency;
	}

	public void setServerprocessorfrequency(String serverprocessorfrequency) {
		this.serverprocessorfrequency = serverprocessorfrequency;
	}

	public String getServerprocessorsmtactive() {
		return serverprocessorsmtactive;
	}

	public void setServerprocessorsmtactive(String serverprocessorsmtactive) {
		this.serverprocessorsmtactive = serverprocessorsmtactive;
	}

	public long getServerprocessorthreadbycore() {
		return serverprocessorthreadbycore;
	}

	public void setServerprocessorthreadbycore(long serverprocessorthreadbycore) {
		this.serverprocessorthreadbycore = serverprocessorthreadbycore;
	}

	public String getServerprocessortype() {
		return serverprocessortype;
	}

	public void setServerprocessortype(String serverprocessortype) {
		this.serverprocessortype = serverprocessortype;
	}

	public Date getServerpurchasedate() {
		return serverpurchasedate;
	}

	public void setServerpurchasedate(Date serverpurchasedate) {
		this.serverpurchasedate = serverpurchasedate;
	}

	public String getServerramsize() {
		return serverramsize;
	}

	public void setServerramsize(String serverramsize) {
		this.serverramsize = serverramsize;
	}

	public String getServertype() {
		return servertype;
	}

	public void setServertype(String servertype) {
		this.servertype = servertype;
	}

	public long getServervirtualizationid() {
		return servervirtualizationid;
	}

	public void setServervirtualizationid(long servervirtualizationid) {
		this.servervirtualizationid = servervirtualizationid;
	}

	public String getServervirtualizationname() {
		return servervirtualizationname;
	}

	public void setServervirtualizationname(String servervirtualizationname) {
		this.servervirtualizationname = servervirtualizationname;
	}


	/**
	 * Application identity class for: org.anaolabs.easytrust.model.etdwh.Server
	 *
	 * Auto-generated by:
	 * org.apache.openjpa.enhance.ApplicationIdTool
	 */
	public static class Id implements Serializable {
		static {
			// register persistent class in JVM
			try { Class.forName("org.anaolabs.easytrust.model.etdwh.Server"); }
			catch(Exception e) {}
		}
	
		public long datekey;
		public int serverid;
	
		public Id() {
		}
	
		public Id(String str) {
			fromString(str);
		}
	
		public long getDatekey() {
			return datekey;
		}
	
		public void setDatekey(long datekey) {
			this.datekey = datekey;
		}
	
		public int getServerid() {
			return serverid;
		}
	
		public void setServerid(int serverid) {
			this.serverid = serverid;
		}
	
		public String toString() {
			return String.valueOf(datekey)
				+ "::" + String.valueOf(serverid);
		}
	
		public int hashCode() {
			int rs = 17;
			rs = rs * 37 + (int) (datekey ^ (datekey >>> 32));
			rs = rs * 37 + serverid;
			return rs;
		}
	
		public boolean equals(Object obj) {
			if(this == obj)
				return true;
			if(obj == null || obj.getClass() != getClass())
				return false;
	
			Id other = (Id) obj;
			return (datekey == other.datekey)
				&& (serverid == other.serverid);
		}
	
		private void fromString(String str) {
			Tokenizer toke = new Tokenizer(str);
			str = toke.nextToken();
			datekey = Long.parseLong(str);
			str = toke.nextToken();
			serverid = Integer.parseInt(str);
		}
	
		protected static class Tokenizer {
			private final String str;
			private int last;
	
			public Tokenizer (String str) {
				this.str = str;
			}
	
			public String nextToken () {
				int next = str.indexOf("::", last);
				String part;
				if(next == -1) {
					part = str.substring(last);
					last = str.length();
				} else {
					part = str.substring(last, next);
					last = next + 2;
				}
				return part;
			}
		}
	}
}