package org.anaolabs.easytrust.model.etfnd;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$ReverseCodeGenerator
 */
public class FndExpDb {
	private long expId;

	private int expIncludePk;

	private int expOrder;

	private String expOwner;

	private String expTableName;

	private String expWhereClause;


	public FndExpDb() {
	}

	public FndExpDb(long expId) {
		this.expId = expId;
	}

	public long getExpId() {
		return expId;
	}

	public void setExpId(long expId) {
		this.expId = expId;
	}

	public int getExpIncludePk() {
		return expIncludePk;
	}

	public void setExpIncludePk(int expIncludePk) {
		this.expIncludePk = expIncludePk;
	}

	public int getExpOrder() {
		return expOrder;
	}

	public void setExpOrder(int expOrder) {
		this.expOrder = expOrder;
	}

	public String getExpOwner() {
		return expOwner;
	}

	public void setExpOwner(String expOwner) {
		this.expOwner = expOwner;
	}

	public String getExpTableName() {
		return expTableName;
	}

	public void setExpTableName(String expTableName) {
		this.expTableName = expTableName;
	}

	public String getExpWhereClause() {
		return expWhereClause;
	}

	public void setExpWhereClause(String expWhereClause) {
		this.expWhereClause = expWhereClause;
	}
}