package org.anaolabs.easytrust.model.etfnd;

import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(schema="ET_FND", name="FND_EXP_DB")
public class FndExpDb {
	@Id
	@Column(name="EXP_ID", length=22)
	private long expId;

	@Basic
	@Column(name="EXP_INCLUDE_PK", length=1)
	private int expIncludePk;

	@Basic
	@Column(name="EXP_ORDER", length=3)
	private int expOrder;

	@Basic
	@Column(name="EXP_OWNER", nullable=false, length=30)
	private String expOwner;

	@Basic
	@Column(name="EXP_TABLE_NAME", nullable=false, length=30)
	private String expTableName;

	@Basic
	@Column(name="EXP_WHERE_CLAUSE", length=4000)
	private String expWhereClause;


	public FndExpDb() {
	}

	public FndExpDb(long expId) {
		this.expId = expId;
	}

	public long getExpId() {
		return expId;
	}

	public void setExpId(long expId) {
		this.expId = expId;
	}

	public int getExpIncludePk() {
		return expIncludePk;
	}

	public void setExpIncludePk(int expIncludePk) {
		this.expIncludePk = expIncludePk;
	}

	public int getExpOrder() {
		return expOrder;
	}

	public void setExpOrder(int expOrder) {
		this.expOrder = expOrder;
	}

	public String getExpOwner() {
		return expOwner;
	}

	public void setExpOwner(String expOwner) {
		this.expOwner = expOwner;
	}

	public String getExpTableName() {
		return expTableName;
	}

	public void setExpTableName(String expTableName) {
		this.expTableName = expTableName;
	}

	public String getExpWhereClause() {
		return expWhereClause;
	}

	public void setExpWhereClause(String expWhereClause) {
		this.expWhereClause = expWhereClause;
	}
}